### ISSUE TITLE
j and k navigtion seems inverted

### ISSUE THREAD

**Issue by CharlesGueunet** [jesseduffield/lazycli#2]
Hello,

Thanks a lot for this nice project, I have a small question concerning the navigation inside the CLI, I usually use j/k instead of arrows and it seems they are inverted compared to vi/vim style (j should goes down). Is this intentional and if so why ?

Cheers,
Charles

**Comment by jesseduffield** [comment]
This is definitely not intentional: I'm not a vim user myself but wanted to provide support for those who were and I always mix those two up!

**Comment by jesseduffield** [comment]
fixed in version v0.1.13
