### ISSUE TITLE
Environment variable configuration?

### ISSUE THREAD

**Issue by lovetoburnswhen** [jesseduffield/lazycli#4]
eg `$LAZYCLI_CONFIG_FILE` to specify the location of `config.yml`

**Comment by jesseduffield** [comment]
done in https://github.com/jesseduffield/lazycli/compare/env-var

**Comment by jesseduffield** [comment]
I've gone with LAZYCLI_CONFIG_DIR just in case I want to put other stuff in that directory down the line
