### ISSUE TITLE
registered_commands to accept partial commands

### ISSUE THREAD

**Issue by michelepagot** [jesseduffield/lazycli#6]
I like to register a command with arguments and arguments could change, e.g.
   ls *.so
   ls /home/paperino

I like to create one unique registered_commands for all of them, something like
profiles:
  - name: ls args
    registered_commands:
      - ls *

where the star is intended as a regular expression to match a set of arguments

**Comment by jesseduffield** [comment]
lemme know if the latest release works for you @michelepagot
